name: This is a github action
run-name: this is the run name
on: [push]
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo test

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: build
        run: echo build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: deploy
        run: echo deploy

      


